### ISSUE TITLE
Platform verification

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/educationplatform#174]
To ensure quality, reliability, and assist future development the education platform should have continuous test and integration capability with adequate coverage of key features.

- [ ] Setup code coverage and reporting

- [ ] Setup static code analysis

- [ ] Create unit tests

- [ ] Setup integration test tool

- [ ] Create integration tests

**Comment by szschaler** [comment]
Partly contributes to #216
