### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by szschaler** [mdenet/educationplatform#36]
- [ ] Document how to set up the running infrastructure
- [ ] Document type conversion logic
- [ ] Document token server architecture
- [ ] Document how to define a new activity and a new tool
- [ ] Document activity loading and storage
